### PR TITLE
Support placement constraint

### PR DESCRIPTION
**Pull request by zuston**

### CODE REVIEW

**Comment by zuston** [comment]
PTAL @oliverhu . This has been tested in our internal hadoop3.2.2 cluster

**Review by oliverhu — APPROVED** [review]

**Comment by oliverhu** [comment]
LGTM, @zuston is there a way add a test for this in one of the integration tests using miniyarn cluster?

**Comment by zuston** [comment]
> LGTM, @zuston is there a way add a test for this in one of the integration tests using miniyarn cluster?

Yes. But this could be included in next PRs, which could be extended with multi hadoop3.x tests mechanism. 

How about merging this firstly?

**Comment by oliverhu** [comment]
Sounds good

**Pull request merged**
